Module: My.BestApp
Items:

  - Resource: BestAppBucket
    Type: AWS::S3::Bucket
    Scope: BestAppFunction
    Allow: ReadWrite

  - Function: BestAppFunction
    Memory: 256
    Timeout: 30
    Sources:

      - Api: POST:/upload
        Invoke: Upload

  - Variable: ApiUrl
    Value: !Ref Module::RestApi::Url
    Scope: public
